# 主数据源的配置文件
mysql:
  # MySQL数据库版本号
  version: 8.3.0
  # MySQL数据库连接URL
  url: jdbc:mysql://kd-pro-mysql:3306?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
  # MySQL数据库账号
  username: root
  # MySQL数据库密码
  password: root

# APIJSON配置

apijson:
  # 是否开启debug模式
  debug: false
  # 是否打印大日志
  isPrintBigLog: false

  maxQueryCount: 2000
  maxUpdateCount: 2000
  maxQueryPage: 10000

# ZZKD配置
zzkd:
  service:
    # 是否启用token验证过滤器
    validate-token-filter-enabled: true
    # ZZKD服务IP地址
    ip: kd-pro-zzkd
    # ZZKD服务端口号
    port: 8081
